apiVersion: v1
kind: Service
metadata: 
  name: strapi-svc
  labels:
    app: strapi
spec: 
  type: NodePort
  ports:
  - port: 80
    targetPort: 1337
    protocol: TCP
  selector: 
    app: strapi
    version: 0.0.1